### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zahoorsolangi** [atiqsamtia/WordPress-App-with-Flutter#12]
AOA
I am new to flutter/dart and have no strong programming background. I have just download your depositary and cloned with vs code but when running I face errors showing in screenshots.
![error 1](https://user-images.githubusercontent.com/21057723/194308244-9ffbfd5f-42bc-4991-ae6a-d9376937efb6.png)
![error 2](https://user-images.githubusercontent.com/21057723/194308251-1500bd15-4712-45c0-b74e-6ba1a6ea7c53.png)

**Comment by atiqsamtia** [comment]
Hey @zahoorsolangi Test with the newest code now, these issues should not occur now, @aliahmad79 did a pull request #13 and now the project is able to run on Android without any issues.
