### ISSUE TITLE
Styling the drawer menu

### ISSUE THREAD

**Issue by LebToki** [atiqsamtia/WordPress-App-with-Flutter#2]
Can you elaborate on how to style this bit too ?

**Comment by atiqsamtia** [comment]
I have redesigned full app, and I'm thinking of removing the drawer and move the categories to Bottom Navigation. 

I'll do this next time when I have time to work on this.

**Comment by atiqsamtia** [comment]
The drawer is removed as it was not needed. Moved categories to a TAB. Please check latest design
