### ISSUE TITLE
line 22 pos 14: 'url != null': is not true.

### ISSUE THREAD

**Issue by milanmaks** [atiqsamtia/WordPress-App-with-Flutter#4]
when i try to load news, this error popup
(2) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/painting/_network_image_io.dart': Failed assertion: line 22 pos 14: 'url != null': is not true.
The relevant error-causing widget was: 
  Author file:///C:/Users/Milan/Desktop/WordPress-App-with-Flutter-master/lib/widgets/post_card.dart:69:66

**Comment by atiqsamtia** [comment]
Please share the full exception log.

**Comment by Nabeel110** [comment]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Author(dirty):
'package:flutter/src/painting/_network_image_io.dart': Failed assertion: line 25 pos 14: 'url != null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Author file:///E:/Flutter_Projects/WordPress-App-with-Flutter/lib/widgets/post_card.dart:69:66
When the exception was thrown, this was the stack: 
#2      new NetworkImage (package:flutter/src/painting/_network_image_io.dart:25:14)
#3      new Image.network (package:flutter/src/widgets/image.dart:409:68)
#4      Author.build (package:wordpress_flutter/widgets/post_card.dart:128:26)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4701:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
...

I am facing the similar error
