### ISSUE TITLE
flutter/src/painting/gradient.dart colors != null error

### ISSUE THREAD

**Issue by emresekeroglu** [atiqsamtia/WordPress-App-with-Flutter#6]
Hi, thanks for your app, but I get an error can you help me

'package:flutter/src/painting/gradient.dart': Failed assertion: line 152 pos 15: 'colors != null': is not true.

{
	"resource": "/Users/emresekeroglu/Desktop/Flutter Projelerim/WordPress-App/lib/pages/post_details.dart",
	"owner": "dart",
	"code": {
		"value": "undefined_named_parameter",
		"target": {
			"$mid": 1,
			"external": "https://dart.dev/tools/diagnostic-messages#undefined_named_parameter",
			"path": "/tools/diagnostic-messages",
			"scheme": "https",
			"authority": "dart.dev",
			"fragment": "undefined_named_parameter"
		}
	},
	"severity": 8,
	"message": "The named parameter 'colors' isn't defined.\nTry correcting the name to an existing named parameter's name, or defining a named parameter with the name 'colors'.",
	"source": "dart",
	"startLineNumber": 42,
	"startColumn": 29,
	"endLineNumber": 42,
	"endColumn": 35,
	"tags": []
}

**Comment by atiqsamtia** [comment]
This is not an issue with this script but a glitch in IDE.

run flutter clean and restart your IDE after that. It'll work fine.

reference. 
https://stackoverflow.com/questions/64168427/flutter-after-flutter-1-22-update-i-am-getting-error-in-lineargradient-propert
